### ISSUE TITLE
Error trying to load local images in basic-mapping page (in PR)

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/wiki#19]
This error applies to this PR https://github.com/beat-saber-modding-group/wiki/pull/18

The `/mapping/basic-mapping.html` page loads without any content, and several errors appear in the console.
![image](https://user-images.githubusercontent.com/27714637/71594142-93963f80-2aeb-11ea-99fa-194bd2c31ac2.png)

Here is an example error message
```
./wiki/mapping/images/arrow-block.PNG 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file) client:159
    errors client:159
    initSocket socket.js:47
    onmessage SockJSClient.js:63
    dispatchEvent sockjs.js:170
    _transportMessage sockjs.js:888
    _transportMessage sockjs.js:886
    emit sockjs.js:86
    onmessage sockjs.js:2962
```

**Comment by megalon** [comment]
It looks like this is caused by the file extension being in uppercase in the markdown file.
If the file extensions are changed to lowercase in the markdown file, the page will load.

Example:
`![Directional Block](./images/arrow-block.PNG)`
changed to
`![Directional Block](./images/arrow-block.png)`

It looks like the file name itself doesn't have to change. This is probably a bug with whatever is loading the images files.

**Comment by lolPants** [comment]
This is not a bug, this is intended behaviour. UNIX based filesystems treat different casing in filenames as distinct files, but Windows does not. The discrepancy between UNIX and Windows is causing the "error".

Just keep file extensions lowercase and everything will be fine.

**Comment by megalon** [comment]
I don't see uppercase file extensions much, and much less try to transfer them between windows and UNIX, so I had no idea that would be an issue.
I'll keep an eye out for it in the future, but it would be nice if the error message was more descriptive.
I wonder why it's showing an unexpected character like that. Is it just Vue.js doing that?
